d = {'content_type': 'document', 'message_id': 3101,
     'from_user': {'id': 1054484091, 'is_bot': False, 'first_name': 'Zharskaya', 'username': None, 'last_name': None, 'language_code': 'ru', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None},
     'date': 1603633416, 'chat': {'id': 1054484091, 'type': 'private', 'title': None, 'username': None, 'first_name': 'Zharskaya', 'last_name': None, 'all_members_are_administrators': None, 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'sticker_set_name': None, 'can_set_sticker_set': None},
     'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_date': None,
     'reply_to_message': {'content_type': 'document', 'message_id': 3090,
    'from_user': '<telebot.types.User object at 0x000002309B19DF70>', 'date': 1603633223,
    'chat': '<telebot.types.Chat object at 0x000002309B19DC10>', 'forward_from': None,
    'forward_from_chat': None, 'forward_from_message_id': None,
    'forward_signature': None, 'forward_date': None, 'reply_to_message': None, 'edit_date': None, 'media_group_id': None, 'author_signature': None,
    'text': None, 'entities': None, 'caption_entities': None, 'audio': None,
    'document': '<telebot.types.Document object at 0x000002309B17D610>',
    'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None,
    'successful_payment': None, 'connected_website': None,
    'json': {'message_id': 3090, 'from': {'id': 1279191350, 'is_bot': True, 'first_name': 'Tas_bot', 'username': 'Assistant_system_bot'},
    'chat': {'id': 1054484091, 'first_name': 'Zharskaya', 'type': 'private'},
    'date': 1603633223, 'document': {'file_name': 'test.jpg', 'mime_type': 'image/jpeg',
    'thumb': {'file_id': 'AAMCAgADGQMAAgwSX5WAR92qiv1VZpkxbDPn7qOEchsAAnQJAALM_alIhxbjGjQ4PXcLqIeZLgADAQAHbQADbTgAAhsE', 'file_unique_id': 'AQADC6iHmS4AA204AAI', 'file_size': 8522, 'width': 226, 'height': 320},
    'file_id': 'BQACAgIAAxkDAAIMEl-VgEfdqor9VWaZMWwz5-6jhHIbAAJ0CQACzP2pSIcW4xo0OD13GwQ', 'file_unique_id': 'AgADdAkAAsz9qUg', 'file_size': 15599}}},
    'edit_date': None, 'media_group_id': None, 'author_signature': None, 'text': None, 'entities': None, 'caption_entities': None, 'audio': None,
     'document': {'file_id': 'BQACAgIAAxkBAAIMHV-VgQgFnwlZZ8s0aehdCkfVNrXhAAJ2CQACzP2pSMJfj6UR0jM2GwQ', 'thumb': '<telebot.types.PhotoSize object at 0x000002309B17D520>',
    'file_name': 'english_pupil.jpg', 'mime_type': 'image/jpeg', 'file_size': 15599},
     'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None,
     'json': {'message_id': 3101, 'from': {'id': 1054484091, 'is_bot': False, 'first_name': 'Zharskaya', 'language_code': 'ru'},
    'chat': {'id': 1054484091, 'first_name': 'Zharskaya', 'type': 'private'}, 'date': 1603633416, 'reply_to_message': {'message_id': 3090,
    'from': {'id': 1279191350, 'is_bot': True, 'first_name': 'Tas_bot', 'username': 'Assistant_system_bot'},
    'chat': {'id': 1054484091, 'first_name': 'Zharskaya', 'type': 'private'}, 'date': 1603633223,
    'document': {'file_name': 'test.jpg', 'mime_type': 'image/jpeg', 'thumb': {'file_id': 'AAMCAgADGQMAAgwSX5WAR92qiv1VZpkxbDPn7qOEchsAAnQJAALM_alIhxbjGjQ4PXcLqIeZLgADAQAHbQADbTgAAhsE', 'file_unique_id': 'AQADC6iHmS4AA204AAI', 'file_size': 8522, 'width': 226, 'height': 320},
    'file_id': 'BQACAgIAAxkDAAIMEl-VgEfdqor9VWaZMWwz5-6jhHIbAAJ0CQACzP2pSIcW4xo0OD13GwQ', 'file_unique_id': 'AgADdAkAAsz9qUg', 'file_size': 15599}},
    'document': {'file_name': 'english_pupil.jpg', 'mime_type': 'image/jpeg', 'thumb': {'file_id': 'AAMCAgADGQEAAgwdX5WBCAWfCVlnyzRp6F0KR9U2teEAAnYJAALM_alIwl-PpRHSMzYLqIeZLgADAQAHbQADbTgAAhsE',
    'file_unique_id': 'AQADC6iHmS4AA204AAI', 'file_size': 8522, 'width': 226, 'height': 320},
    'file_id': 'BQACAgIAAxkBAAIMHV-VgQgFnwlZZ8s0aehdCkfVNrXhAAJ2CQACzP2pSMJfj6UR0jM2GwQ', 'file_unique_id': 'AgADdgkAAsz9qUg', 'file_size': 15599}}}
# for i in d.keys():
    # print(i , d[i])
print(d['document'])
